// <auto-generated />
using System;
using HilbertoSilva.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HilbertoSilva.Migrations
{
    [DbContext(typeof(EscolaDbContext))]
    [Migration("20260525225914_AlterarAnoEscolarParaEnum")]
    partial class AlterarAnoEscolarParaEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HilbertoSilva.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CpfResponsavel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf_responsavel");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_nascimento");

                    b.Property<int?>("FkTurma")
                        .HasColumnType("int")
                        .HasColumnName("fk_turma");

                    b.Property<int>("FkUsuario")
                        .HasColumnType("int")
                        .HasColumnName("fk_usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_responsavel");

                    b.Property<string>("TelefoneResponsavel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefone_responsavel");

                    b.HasKey("Id");

                    b.HasIndex("FkTurma");

                    b.HasIndex("FkUsuario")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Boletim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("boletim_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FkAluno")
                        .HasColumnType("int")
                        .HasColumnName("fk_aluno");

                    b.Property<int>("FkTurmaDisciplina")
                        .HasColumnType("int")
                        .HasColumnName("fk_turma_disciplina");

                    b.Property<decimal?>("Frequencia")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("frequencia");

                    b.Property<decimal?>("NotaU1")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nota_u1");

                    b.Property<decimal?>("NotaU2")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nota_u2");

                    b.Property<decimal?>("NotaU3")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nota_u3");

                    b.HasKey("Id");

                    b.HasIndex("FkTurmaDisciplina");

                    b.HasIndex("FkAluno", "FkTurmaDisciplina")
                        .IsUnique()
                        .HasDatabaseName("aluno_materia_unico");

                    b.ToTable("Boletins");
                });

            modelBuilder.Entity("HilbertoSilva.Models.DiarioClasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("turma_disciplina_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FkDisciplina")
                        .HasColumnType("int")
                        .HasColumnName("fk_disciplina");

                    b.Property<int>("FkProfessor")
                        .HasColumnType("int")
                        .HasColumnName("fk_professor");

                    b.Property<int>("FkTurma")
                        .HasColumnType("int")
                        .HasColumnName("fk_turma");

                    b.HasKey("Id");

                    b.HasIndex("FkDisciplina");

                    b.HasIndex("FkProfessor");

                    b.HasIndex("FkTurma");

                    b.ToTable("DiarioClasse");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("disciplina_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int")
                        .HasColumnName("carga_horaria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("professor_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("especialidade");

                    b.Property<int>("FkUsuario")
                        .HasColumnType("int")
                        .HasColumnName("fk_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("FkUsuario")
                        .IsUnique();

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoEscolar")
                        .HasColumnType("int")
                        .HasColumnName("ano_escolar");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int")
                        .HasColumnName("ano_letivo");

                    b.Property<string>("NomeTurma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome_turma");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("turno");

                    b.HasKey("Id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Aluno", b =>
                {
                    b.HasOne("HilbertoSilva.Models.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("FkTurma")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HilbertoSilva.Models.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("HilbertoSilva.Models.Aluno", "FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Boletim", b =>
                {
                    b.HasOne("HilbertoSilva.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("FkAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HilbertoSilva.Models.DiarioClasse", "DiarioClasse")
                        .WithMany("Boletins")
                        .HasForeignKey("FkTurmaDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("DiarioClasse");
                });

            modelBuilder.Entity("HilbertoSilva.Models.DiarioClasse", b =>
                {
                    b.HasOne("HilbertoSilva.Models.Disciplina", "Disciplina")
                        .WithMany("DiariosClasses")
                        .HasForeignKey("FkDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HilbertoSilva.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("FkProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HilbertoSilva.Models.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("FkTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Professor", b =>
                {
                    b.HasOne("HilbertoSilva.Models.Usuario", "Usuario")
                        .WithOne("Professor")
                        .HasForeignKey("HilbertoSilva.Models.Professor", "FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HilbertoSilva.Models.DiarioClasse", b =>
                {
                    b.Navigation("Boletins");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Disciplina", b =>
                {
                    b.Navigation("DiariosClasses");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("HilbertoSilva.Models.Usuario", b =>
                {
                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });
#pragma warning restore 612, 618
        }
    }
}
